#!/bin/bash

# Usage info
usage_1="Usage 1: pmenu WANTED_CREDENTIAL_INFO [DMENU_ARGS...]"
usage_2="Usage 2: pmenu list-credentials"
usage="$usage_1\n$usage_2"

# To keep things clean
shopt -s nullglob globstar

# Get optional subcommand
subcommand="${1:-nothing}"

# Get name for wanted pass entry (inside $password)
prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu)

# "list-credentials" subcommand just lists the available credentials associated to the chosen pass entry
if [[ $subcommand == "list-credentials" ]]; then
    # TODO: refine output
    notify-send "$(pass show "$password")"

    exit 0
elif [[ $subcommand != "nothing" ]]; then
    echo -e "$usage"

    exit 1
fi

# Get wanted credential field for chosen entry

echo $password
echo shit

available_fields="$(/sul/get-credentials $password 2>&1)"
if [ $? -ne 0 ]; then notify-send "ERROR: $available_fields"; exit 1; fi
available_fields="pw\n$available_fields"
field=$(echo -e "$available_fields" | dmenu -p "field: ")

echo ok

[[ -n $password ]] || exit

if [[ "$field" == "pw" ]]; then
    # NB. If error, notify, else put in clipboard
    OUT=$(pass show "$password" 2>&1)
    if [ $? -ne 0 ]; then
        notify-send "ERROR: $OUT"
    else
        echo "$OUT" | head -n1 | xclip -selection clipboard
        notify-send "Password copied to clipboard"
    fi
else
    field_val=$(pass show "$password" | grep "^$field:")
    [[ -z "$field_val" ]] && { echo "$field does not exist for $password"; exit 1; }
    echo "$field_val" | cut -d' ' -f2 | xclip -selection clipboard
fi
